### ISSUE TITLE
QA: editorconfig-cli support autofix?

### ISSUE THREAD

**Issue by akaguny** [htmlacademy/editorconfig-cli#14]

**Comment by zeckson** [comment]
Nope, currently it's not.

**Comment by akaguny** [comment]
You are planning this feature?

**Comment by zeckson** [comment]
Actually this feature depends on syntactiacal analysis of code, since it's not possible to decide if code padding should be increased or decreased if the language is not known.
Let's assume simple example:
I have a js-program, and I have a configuration to use 4 spaces. In this case I have the following code:
```js
var a;
if (condition) {
    a = `weather is good!`;
  } else { // The line is padded by 2 spaces;
    a = `weather is bad!`;
}
```
So in this case I have to know that the text is actually is `javascript` and should be padded by 0 pads.
In the oposite case for `HTML`:
```html
<div class="outer">
    <p>First paragraph</p>
  <hr/> <--This is padded by 2 spaces -->
    <p>Second paragraph</p>
</div>
```
In this case I have to pad by 4 spaces instead, since it's `HTML`.

So since this is currently a very simple tool which just alerts that's something is wrong to autoreformat correctly you should use language specific instruments such as `eslint`, prettifiers and so on, which depends on syntax of text.

So to make the story short — no it's not planned so far.
